### PR TITLE
Switch to using sqlalchemy instead of raw psycopg2

### PR DESCRIPTION
**Pull request by njsmith**
This is a bit of an experiment. The idea is to lay the groundwork for
more complex features in the future that need non-trivial data
persistence.

### CODE REVIEW

**Comment by webknjaz** [comment]
Why do you use synchronous DB access?

**Comment by njsmith** [comment]
@webknjaz Because we don't have mature Trio db libraries yet. And, we have a tiny db, tiny queries, very low latency between the app and the db, and tiny amounts of load. So in practice using sync db access just doesn't matter here; we can treat it as instantaneous. (Though eventually it would be nice to switch to a proper async database setup, just for general cleanliness.)

**Comment by webknjaz** [comment]
Fair enough

**Comment by webknjaz** [comment]
FTR heroku had an outage today, right in the middle of my workshop. JFYI if you see some weird behavior why redeploying the bot. So maybe postpone it till tomorrow.

**Pull request merged**
